### ISSUE TITLE
Placing an icon in the Markdown frontmatter title

### ISSUE THREAD

**Issue by Hecatron** [louisescher/starlight-ion-theme#1]
So one thing I've noticed is that if you try and place the icon for a page in the title field of a markdown page like this.

```yaml
---
title: "[box] Example Page"
description: An Example Page.
---
```

The above will add the icon to the sidebar, but also add the text "[box]" to the page title on the viewed page.
One workaround to this (took me a while to figure out) is to place the icon in the sidebar object like this instead
```yaml
---
title: "Example Page"
description: An Example Page.
sidebar: {label: "[box] Example Page"}
---
```

Just thought to mention it in case it's worth adding to the docs
